package fiberapi

import "github.com/fruitspace/HyprrSpace/models/structs"

var ProductGDTariffs = map[string]structs.GDTariff{
	"1": {
		Title:       "Press Start",
		PriceRUB:    0,
		PriceUSD:    0,
		Players:     100,
		Levels:      500,
		Comments:    -1,
		Posts:       -1,
		CustomMusic: false,
		Music:       structs.GDTariffMusic{Files: true},
		GDLab:       structs.GDTariffBuildlab{},
		ACL:         false,
		Shops:       false,
		Roles:       false,
		Modules:     false,
		Backups:     false,
		Logs:        false,
		Levelpacks:  false,
		Quests:      false,
	},
	"2": {
		Title:       "Singularity",
		PriceRUB:    50,
		PriceUSD:    1.5,
		Players:     -1,
		Levels:      -1,
		Comments:    -1,
		Posts:       -1,
		CustomMusic: true,
		Music: structs.GDTariffMusic{
			YouTube: true,
		},
		GDLab: structs.GDTariffBuildlab{
			Enabled:  true,
			IOS:      false,
			MacOS:    false,
			Icons:    true,
			Textures: false,
			MultiVer: true,
			Extended: false,
		},
		ACL:        false,
		Shops:      false,
		Roles:      true,
		Modules:    false,
		Backups:    false,
		Logs:       true,
		Levelpacks: true,
		Quests:     true,
	},
	"3": {
		Title:       "Takeoff",
		PriceRUB:    100,
		PriceUSD:    3,
		Players:     -1,
		Levels:      -1,
		Comments:    -1,
		Posts:       -1,
		CustomMusic: true,
		Music: structs.GDTariffMusic{
			YouTube: true,
			Deezer:  true,
			VK:      true,
			Files:   true,
		},
		GDLab: structs.GDTariffBuildlab{
			Enabled:  true,
			IOS:      true,
			MacOS:    true,
			Icons:    true,
			Textures: true,
			MultiVer: true,
			Extended: false,
		},
		ACL:        false,
		Shops:      false,
		Roles:      true,
		Modules:    true,
		Backups:    true,
		Logs:       true,
		Levelpacks: true,
		Quests:     true,
	},
	"4": {
		Title:       "Foundation",
		PriceRUB:    150,
		PriceUSD:    5,
		Players:     -1,
		Levels:      -1,
		Comments:    -1,
		Posts:       -1,
		CustomMusic: true,
		Music: structs.GDTariffMusic{
			YouTube: true,
			Deezer:  true,
			VK:      true,
			Files:   true,
		},
		GDLab: structs.GDTariffBuildlab{
			Enabled:  true,
			IOS:      true,
			MacOS:    true,
			Icons:    true,
			Textures: true,
			MultiVer: true,
			Extended: true,
		},
		ACL:        true,
		Shops:      true,
		Roles:      true,
		Modules:    true,
		Backups:    true,
		Logs:       true,
		Levelpacks: true,
		Quests:     true,
	},
}

var ProductMCTariffs = map[string]structs.MCTariff{
	"d1": {
		Title:     "Next ⋙",
		PriceRUB:  350,
		CPU:       1,
		MinRamGB:  2,
		MaxRamGB:  4,
		IsDynamic: true,
		DiskGB:    20,
	},
	"d2": {
		Title:     "Reforged",
		PriceRUB:  700,
		CPU:       2,
		MinRamGB:  4,
		MaxRamGB:  8,
		IsDynamic: true,
		DiskGB:    30,
	},
	"d3": {
		Title:     "EverPeak",
		PriceRUB:  1300,
		CPU:       3,
		MinRamGB:  8,
		MaxRamGB:  12,
		IsDynamic: true,
		DiskGB:    45,
	},
	"d4": {
		Title:     "Orbital",
		PriceRUB:  1700,
		CPU:       4,
		MinRamGB:  8,
		MaxRamGB:  16,
		IsDynamic: true,
		DiskGB:    60,
	},
	"d5": {
		Title:     "Horizon",
		PriceRUB:  2600,
		CPU:       5,
		MinRamGB:  16,
		MaxRamGB:  24,
		IsDynamic: true,
		DiskGB:    100,
	},

	"s1": {
		Title:     "Air",
		PriceRUB:  550,
		CPU:       1,
		MinRamGB:  4,
		MaxRamGB:  4,
		IsDynamic: false,
		DiskGB:    30,
	},
	"s2": {
		Title:     "Viper",
		PriceRUB:  1000,
		CPU:       2,
		MinRamGB:  8,
		MaxRamGB:  8,
		IsDynamic: false,
		DiskGB:    40,
	},
	"s3": {
		Title:     "Carbon",
		PriceRUB:  1500,
		CPU:       3,
		MinRamGB:  12,
		MaxRamGB:  12,
		IsDynamic: false,
		DiskGB:    60,
	},
	"s4": {
		Title:     "Proton",
		PriceRUB:  2300,
		CPU:       4,
		MinRamGB:  16,
		MaxRamGB:  16,
		IsDynamic: false,
		DiskGB:    80,
	},
	"s5": {
		Title:     "Horizon",
		PriceRUB:  3200,
		CPU:       5,
		MinRamGB:  24,
		MaxRamGB:  24,
		IsDynamic: false,
		DiskGB:    120,
	},
}

const ProductMCDedicatedIPPrice = 100
const ProductMCAdditionalDiskPricePer10GB = 50
const ProductMCMySQLDBPrice = 0
