package fiberapi

import "github.com/fruitspace/FiberAPI/models/structs"

var ProductGDTariffs = map[string]structs.GDTariff{
	"1": {
		Title:        "Press Start",
		PriceRUB:     0,
		PriceUSD:     0,
		Players:      100,
		Levels:       500,
		Comments:     -1,
		Posts:        -1,
		CustomMusic:  false,
		Music:        structs.GDTariffMusic{Files: true},
		GDLab:        structs.GDTariffBuildlab{},
		ACL:          false,
		Shops:        false,
		Roles:        false,
		CustomChests: false,
		Modules:      false,
		Backups:      false,
		Logs:         false,
		Levelpacks:   false,
		Quests:       false,
	},
	"2": {
		Title:       "Singularity",
		PriceRUB:    50,
		PriceUSD:    1.5,
		Players:     -1,
		Levels:      -1,
		Comments:    -1,
		Posts:       -1,
		CustomMusic: true,
		Music: structs.GDTariffMusic{
			YouTube: true,
			Deezer:  false,
			VK:      false,
			Files:   true,
		},
		GDLab: structs.GDTariffBuildlab{
			Enabled:  true,
			IOS:      false,
			MacOS:    false,
			Icons:    true,
			Textures: false,
			V22:      true,
		},
		ACL:          false,
		Shops:        true,
		Roles:        true,
		CustomChests: false,
		Modules:      false,
		Backups:      false,
		Logs:         true,
		Levelpacks:   true,
		Quests:       true,
	},
	"3": {
		Title:       "Takeoff",
		PriceRUB:    100,
		PriceUSD:    3,
		Players:     -1,
		Levels:      -1,
		Comments:    -1,
		Posts:       -1,
		CustomMusic: true,
		Music: structs.GDTariffMusic{
			YouTube: true,
			Deezer:  true,
			VK:      true,
			Files:   true,
		},
		GDLab: structs.GDTariffBuildlab{
			Enabled:  true,
			IOS:      true,
			MacOS:    true,
			Icons:    true,
			Textures: true,
			V22:      true,
		},
		ACL:          true,
		Shops:        true,
		Roles:        true,
		CustomChests: true,
		Modules:      true,
		Backups:      true,
		Logs:         true,
		Levelpacks:   true,
		Quests:       true,
	},
}
